### ISSUE TITLE
Add default pipe for dates?

### ISSUE THREAD

**Issue by pdehaan** [gchumillas/schema-fixer#1]
Was playing with the library and got a bit stuck at what to do w/ Date objects.

I tried casting as `"string"` but it didn't like that, and there wasn't a pipe for `"object"`. I was able to pipe to `"number"` which seems to call `.getTime()`, I think.

Not sure if a built-in pipe for Date objects would be generally useful. If it receives a Number value, it could do `new Date(value)`, if it receives a Date value, pass it through as-is, if it receives a String value maybe it does some `Date.parse()` or something. Possibly defaults to the current date if no date provided.

**Comment by gchumillas** [comment]
Hi, you can create your own pipe. For example:

```js
import { fix, pipes, pipe, ok, error } from '@gchumillas/schema-fixer'
const { string } = pipes

// This pipe evaluates and fixes any date.
// It returns the fixed date in ISO format.
const date = pipe((value) => {
  const milliseconds = Date.parse(`${value}`)
  if (isNaN(milliseconds)) {
    return error('Not a recognizable date format.')
  }

  const date = new Date(milliseconds)
  return ok(date.toISOString())
})

// outputs: 1995-12-04T00:12:00.000Z
const r1 = fix('04 Dec 1995 00:12:00 GMT', date())
console.log(r1)

// or applied on a complex object
// outputs: { title: 'JavaScript Release', date: '1995-12-04T00:12:00.000Z' }
const r2 = fix({
  title: 'JavaScript Release',
  date: '04 Dec 1995 00:12:00 GMT'
}, {
  title: string(),
  date: date()
})
console.log(r2)
```

**Comment by gchumillas** [comment]
By the way, I just added the `date` pipe in the current release:
https://github.com/gchumillas/schema-fixer/blob/master/src/index.test.js#L165

**Comment by pdehaan** [comment]
> By the way, I just added the `date` pipe in the current release

Beautiful, thanks! ❤️
